name: Fetch the blockchain data and dump data on json format every 1 hour
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 0 * *'
permissions:
  contents: write
  packages: write
jobs:
  data-fetch-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
       
      - name: Install dependencies
        run: pip install -r requirements.txt
       
      - name: Run script
        run: python3 tx.py

      # - name: Upload transactions.json to S3
      #   run: aws s3 cp transactions.json s3://0x219ab540356cbb839cbe05303d7705fa/transactions.json
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add transactions.json
          git commit -m "Update transactions.json" || echo "No changes to commit"
          git push   
